### ISSUE TITLE
Add graphs to styleguide

### ISSUE THREAD

**Issue by bobvanluijt** [SeMI-network/semi-website#120]
A new page met an overview of available graphs should be available in the style guide.

Todo:
- [ ] Create a graph style page on the [styleguide](https://www.semi.network/styleguide/) (equivalent [markdown](https://github.com/SeMI-network/semi-website/tree/develop/styleguide)).
- [ ] Add a two colum setup with an example of the graph on the left side and implementation documentation on the right side (with code snippet).
- [ ] Make sure that the graph contains the correct style schema's from the [orignal SASS files](https://github.com/SeMI-network/semi-website/tree/develop/css).
- [ ] Make sure that the graphs contains approriate tests.
- [ ] Add tests to [travis-ci](https://github.com/SeMI-network/semi-website/blob/develop/.travis.yml)
- [ ] Create pull request for develop branch.

### Example

The graph below is one example of such a graph, the example on the page should be an actual canvas (not a screen shot).

<img width="306" alt="screen shot 2018-09-02 at 17 48 19" src="https://user-images.githubusercontent.com/5509162/45287318-3e927c80-b4e8-11e8-982f-df068141e734.png">

**Comment by chrischne** [comment]
Can you clarify the end goal of this. I am asking because the current implementation of the [playground](https://github.com/SeMI-network/semi-playground-prototype) is implemented in [Vue](https://vuejs.org/) and the Example "canvas" you are showing uses the [vue-google-charts](https://www.npmjs.com/package/vue-google-charts) for the sankey with some configuration object for adjusting the colors. Does it make sense to add vue snippets to the styleguide? Providing HTML/CSS means to rewrite the code.

**Comment by bobvanluijt** [comment]
Please do, please also include all other charts. The Styleguide itself is a great example of how such a page should look (with documentation, explanation etc). Please issue all charts as a pull request.

**Comment by bobvanluijt** [comment]
Hi @chrischne,

This is a good start, however, there are a few things that currently are missing.

# Code Snippets

The goal of the code snippet is that one can understand how to simply add the graph, and have it working. For example the Sankey Diagram, how do I use it? Try to make it as compact and clear as possible.

# Be Clean and Precice

This one is very -if not the most- important. Currently it is all quite messy, some examples based on the Sankey Diagram.

- why not fonts from the style guide?
- why are there comments in the code snippet?
- why are there hardcoded colors? Why not directly reference to the style guide.

# Why not create a library, like: "semi-graphs.js"?

Why not create a library, that people can super easily use the graphs in there?

That one can do something like;

```javascript
SeMI.charts.load('sankey-diagram', {
    // some data
)
```

That's it, you can abstract everything away.

# Miscelenious

- We use [GitFlow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) so the branch-name should be `feature/graph-style`.
- Why not add them to the styleguide page as "atoms" (@StudioSpindle, graphs are atoms, right?).
- There are errors in the JS code.

**Comment by StudioSpindle** [comment]
I think it would identify as a molecule. Because you could dissect the Sankey into smaller atoms such as the labels, colored bars, and connections. Each has a style which could be made generic so it can be used in other charts styles as well.

**Comment by chrischne** [comment]
Hi Remi (@StudioSpindle),

I need to add some css classes which I use in the graphs to the [orignal SASS files](https://github.com/SeMI-network/semi-website/tree/develop/css). I need some help in putting them to an appropriate place.  Should I e.g. add them as follows?

`@import 'molecule-charts';`

Thanks for some input. 

Christian

**Comment by chrischne** [comment]
Hi @bobvanluijt  

Please have a look at [feature/graph-style](https://github.com/SeMI-network/semi-website/tree/graph-style). 

**Charts**
The following charts are implemented:

- Sankey Diagram
- Bubble Chart
- Force-Directed Graph
- Constraint-Based Layout
- Beeswarm Chart

All charts come along as a function of the following form:

`someChart('id-of-parent-container',data, options)`

**Options**
The charts have a section _Chart Options_ which allow to configure a chart. Options include things like width and height of the chart, paddings, but also options for defining how data has to be mapped, grouped or coloured. 

**Demo Data**
The demo data is moved to _graph-demo-data.js_ in order to unclutter the code snippets. 

**SASS/Styling**
@StudioSpindle , could you look at [_component-charts.scss](https://github.com/SeMI-network/semi-website/blob/feature/graph-style/css/_sass/_component-charts.scss) to check if the class names need to be adapted. 

All the styling is done through SASS where possible. The _sankeyDiagram()_ is based on google charts and the google charts options only allow for passing actual colours, not classes. So the sankey colours are hardcoded. The circles in _beeswarm()_ are canvas based, so styles cannot be passed through css. Although an svg based beeswarm is possible, it makes sense to have it canvas based for performance reasons. Only the circles are drawn on canvas, tooltips and axis are html/svg. 

**Dependencies**
There are several libraries on which the charts depend on. A possibility could be to create an own repository for the chart library instead of being part of the website. There we could bundle everything nicely into a library and then integrate the bundled version into the style guide. This would also allow to use ES6 for development (-> classes etc.)

Please note that the code snippets need to be copy&pasted to an environment where _style-sg.css_ and the fonts are loaded in order for them to run properly.

**Comment by bobvanluijt** [comment]
Thanks, @chrischne, we are almost there 👍 

1. Currently the functions (`someChart('id-of-parent-container',data, options)`) are added to the root. Please encapusalte them in `SeMI.charts.someChart('id-of-parent-container',data, options)`.
2. Please dynamically load scripts needed. For example if `https://www.gstatic.com/charts/loader.js` is needed load this in the `someChart()` function.
3. Please load _all_ scripts from `www.semi.network/*`, not via rawgit.com or any other domain. You can also use jekyll to show the current URL. You will find this in the config YAML file under `url`.
4. Please use the appropriate code highlighting.

**Comment by chrischne** [comment]
Hi @bobvanluijt 

Please have a look at the current state: 

- Charts are now accessible as `semi.charts.someChart('id-of-parent-container',data, options)`. 
- Everything is encapsulated. 
- Dependencies are dynamically loaded as needed. 
- `semi-charts.js` and `semi-demo-data.js` are loaded from `www.semi.network/*`. Dependency libraries are loaded from their official cdn's. Please note that e.g. `https://www.semi.network/js/semi-charts.js` will only become available once merged. Serving `https://www.gstatic.com/charts/loader.js` on `https://www.semi.network` would be against the [terms of service](https://developers.google.com/chart/interactive/faq)
- I see that there is highlight.js is loaded in the website. None of the code snippets on the style guide seem to be highlighted. Don't know if that is intentional? I currently left the code in the same style as the html snippets.

**Comment by bobvanluijt** [comment]
hi @chrischne,

Sorry for the late response.

Great to see, to your last bullet, yes this is correct because it is occasionally used when the code is involved. Of course, this could be done more sophisticated but it is okay for now.

How far are you with this milestone?

**Comment by chrischne** [comment]
All remaining four points you mentioned above are solved except the code highlighting. If I add `<pre><code>...</code></pre>` as in the highlight.js docs. The font gets way too large. Is there an example somewhere where code is highlighted in the style guide (I didn't find any after a short search)

**Comment by StudioSpindle** [comment]
@bobvanluijt what's te status of this?

**Comment by bobvanluijt** [comment]
Currently obsolete
