### ISSUE TITLE
Create dedicated Keyper page as subpage of products

### ISSUE THREAD

**Issue by carne-vore** [SeMI-network/semi-website#254]
As discussed in meeting on 7 Feb

**Comment by carne-vore** [comment]
YupOp 7 feb. 2019 14:29 schreef rafaelcanalesduron <notifications@github.com>:@carne-vore you are providing content for this one first too, right?

**Comment by carne-vore** [comment]
Keyper logo
Keyper 

Govern your custom networks with Keyper

Keyper is a simple tool that helps you to create and manage networks. You can create keys for your peers and with Weaviate Whitelabel Platform you can monetize the network queries if desired.

(I am sourcing some more info to fill the page)

**Comment by rafaelcanalesduron** [comment]
Added a reference page in zeplin: https://zpl.io/awWAd4K
@carne-vore on the second USP we could use a different title instead of "communicating changes". To me it sounds like the value of it is that your networks are kept updated automatically, so we could say something like "Automatic updates for your networks".

**Comment by carne-vore** [comment]
new version pushed to branch - pls check @rafaelcanalesduron
